package team.a9043.yiluwiki.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import team.a9043.yiluwiki.entity.YwPage;
import team.a9043.yiluwiki.entity.YwPageExample;

public interface YwPageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_page
     *
     * @mbg.generated Sat Oct 27 00:55:06 CST 2018
     */
    long countByExample(YwPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_page
     *
     * @mbg.generated Sat Oct 27 00:55:06 CST 2018
     */
    int deleteByExample(YwPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_page
     *
     * @mbg.generated Sat Oct 27 00:55:06 CST 2018
     */
    int deleteByPrimaryKey(Integer ypId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_page
     *
     * @mbg.generated Sat Oct 27 00:55:06 CST 2018
     */
    int insert(YwPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_page
     *
     * @mbg.generated Sat Oct 27 00:55:06 CST 2018
     */
    int insertSelective(YwPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_page
     *
     * @mbg.generated Sat Oct 27 00:55:06 CST 2018
     */
    List<YwPage> selectByExampleWithBLOBs(YwPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_page
     *
     * @mbg.generated Sat Oct 27 00:55:06 CST 2018
     */
    List<YwPage> selectByExample(YwPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_page
     *
     * @mbg.generated Sat Oct 27 00:55:06 CST 2018
     */
    YwPage selectByPrimaryKey(Integer ypId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_page
     *
     * @mbg.generated Sat Oct 27 00:55:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") YwPage record, @Param("example") YwPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_page
     *
     * @mbg.generated Sat Oct 27 00:55:06 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") YwPage record, @Param("example") YwPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_page
     *
     * @mbg.generated Sat Oct 27 00:55:06 CST 2018
     */
    int updateByExample(@Param("record") YwPage record, @Param("example") YwPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_page
     *
     * @mbg.generated Sat Oct 27 00:55:06 CST 2018
     */
    int updateByPrimaryKeySelective(YwPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_page
     *
     * @mbg.generated Sat Oct 27 00:55:06 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(YwPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_page
     *
     * @mbg.generated Sat Oct 27 00:55:06 CST 2018
     */
    int updateByPrimaryKey(YwPage record);
}